/*
 * Created on 18 十月 2017 ( Time 09:23:54 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package cn.mxlog.sscloud.model;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "combo"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="combo", catalog="ss_cloud" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="Combo.countAll", query="SELECT COUNT(X) FROM Combo x" )
} )
public class Combo implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="name", length=255)
    private String     name         ;

    @Column(name="traffic")
    private Long     traffic      ;

    @Column(name="traffic_name", length=255)
    private String     trafficName  ;

    @Column(name="period")
    private Integer     period       ;

    @Column(name="price")
    private BigDecimal price        ;

    @Column(name="sale_price")
    private BigDecimal salePrice    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdate")
    private Date       createdate   ;

    @Column(name="createby", length=255)
    private String     createby     ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modifydate")
    private Date       modifydate   ;

    @Column(name="modifyby", length=255)
    private String     modifyby     ;

    @Column(name="status")
    private Integer    status       ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Combo() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : name ( VARCHAR ) 
    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }

    //--- DATABASE MAPPING : traffic ( VARCHAR ) 
    public void setTraffic( Long traffic ) {
        this.traffic = traffic;
    }
    public Long getTraffic() {
        return this.traffic;
    }

    //--- DATABASE MAPPING : traffic_name ( VARCHAR ) 
    public void setTrafficName( String trafficName ) {
        this.trafficName = trafficName;
    }
    public String getTrafficName() {
        return this.trafficName;
    }

    //--- DATABASE MAPPING : period ( VARCHAR ) 
    public void setPeriod( Integer period ) {
        this.period = period;
    }
    public Integer getPeriod() {
        return this.period;
    }

    //--- DATABASE MAPPING : price ( DECIMAL ) 
    public void setPrice( BigDecimal price ) {
        this.price = price;
    }
    public BigDecimal getPrice() {
        return this.price;
    }

    //--- DATABASE MAPPING : sale_price ( DECIMAL ) 
    public void setSalePrice( BigDecimal salePrice ) {
        this.salePrice = salePrice;
    }
    public BigDecimal getSalePrice() {
        return this.salePrice;
    }

    //--- DATABASE MAPPING : createdate ( DATETIME ) 
    public void setCreatedate( Date createdate ) {
        this.createdate = createdate;
    }
    public Date getCreatedate() {
        return this.createdate;
    }

    //--- DATABASE MAPPING : createby ( VARCHAR ) 
    public void setCreateby( String createby ) {
        this.createby = createby;
    }
    public String getCreateby() {
        return this.createby;
    }

    //--- DATABASE MAPPING : modifydate ( DATETIME ) 
    public void setModifydate( Date modifydate ) {
        this.modifydate = modifydate;
    }
    public Date getModifydate() {
        return this.modifydate;
    }

    //--- DATABASE MAPPING : modifyby ( VARCHAR ) 
    public void setModifyby( String modifyby ) {
        this.modifyby = modifyby;
    }
    public String getModifyby() {
        return this.modifyby;
    }

    //--- DATABASE MAPPING : status ( INT ) 
    public void setStatus( Integer status ) {
        this.status = status;
    }
    public Integer getStatus() {
        return this.status;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(name);
        sb.append("|");
        sb.append(traffic);
        sb.append("|");
        sb.append(trafficName);
        sb.append("|");
        sb.append(period);
        sb.append("|");
        sb.append(price);
        sb.append("|");
        sb.append(salePrice);
        sb.append("|");
        sb.append(createdate);
        sb.append("|");
        sb.append(createby);
        sb.append("|");
        sb.append(modifydate);
        sb.append("|");
        sb.append(modifyby);
        sb.append("|");
        sb.append(status);
        return sb.toString(); 
    } 

}
