/*
 * Created on 18 十月 2017 ( Time 09:23:54 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package cn.mxlog.sscloud.model;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "server_log"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="server_log", catalog="ss_cloud" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ServerLog.countAll", query="SELECT COUNT(X) FROM ServerLog x" )
} )
public class ServerLog implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="server", nullable=false, length=255)
    private String     server       ;

    @Column(name="traffic")
    private Long       traffic      ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdate")
    private Date       createdate   ;

    @Column(name="createby", length=255)
    private String     createby     ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modifydate")
    private Date       modifydate   ;

    @Column(name="modifyby", length=255)
    private String     modifyby     ;

    @Column(name="status")
    private Integer    status       ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ServerLog() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : server ( VARCHAR ) 
    public void setServer( String server ) {
        this.server = server;
    }
    public String getServer() {
        return this.server;
    }

    //--- DATABASE MAPPING : traffic ( BIGINT ) 
    public void setTraffic( Long traffic ) {
        this.traffic = traffic;
    }
    public Long getTraffic() {
        return this.traffic;
    }

    //--- DATABASE MAPPING : createdate ( DATETIME ) 
    public void setCreatedate( Date createdate ) {
        this.createdate = createdate;
    }
    public Date getCreatedate() {
        return this.createdate;
    }

    //--- DATABASE MAPPING : createby ( VARCHAR ) 
    public void setCreateby( String createby ) {
        this.createby = createby;
    }
    public String getCreateby() {
        return this.createby;
    }

    //--- DATABASE MAPPING : modifydate ( DATETIME ) 
    public void setModifydate( Date modifydate ) {
        this.modifydate = modifydate;
    }
    public Date getModifydate() {
        return this.modifydate;
    }

    //--- DATABASE MAPPING : modifyby ( VARCHAR ) 
    public void setModifyby( String modifyby ) {
        this.modifyby = modifyby;
    }
    public String getModifyby() {
        return this.modifyby;
    }

    //--- DATABASE MAPPING : status ( INT ) 
    public void setStatus( Integer status ) {
        this.status = status;
    }
    public Integer getStatus() {
        return this.status;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(server);
        sb.append("|");
        sb.append(traffic);
        sb.append("|");
        sb.append(createdate);
        sb.append("|");
        sb.append(createby);
        sb.append("|");
        sb.append(modifydate);
        sb.append("|");
        sb.append(modifyby);
        sb.append("|");
        sb.append(status);
        return sb.toString(); 
    } 

}
