/*
 * Created on 18 十月 2017 ( Time 09:23:54 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package cn.mxlog.sscloud.model;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

/**
 * Persistent class for entity stored in table "server"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="server", catalog="ss_cloud" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="Server.countAll", query="SELECT COUNT(X) FROM Server x" )
} )
public class Server implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="name", length=255)
    private String     name         ;

    @Column(name="region", length=255)
    private String     region       ;

    @Column(name="ip", length=255)
    private String     ip           ;

    @Column(name="port", length=255)
    private String     port         ;

    @Column(name="user", length=255)
    private String     user         ;

    @Column(name="user_pwd", length=255)
    private String     userPwd      ;

    @Column(name="traffic")
    private Long       traffic      ;

    @Column(name="traffic_name", length=64)
    private String     trafficName  ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdate")
    private Date       createdate   ;

    @Column(name="createby", length=255)
    private String     createby     ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modifydate")
    private Date       modifydate   ;

    @Column(name="modifyby", length=255)
    private String     modifyby     ;

    @Column(name="status")
    private Integer    status       ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Server() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : name ( VARCHAR ) 
    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }

    //--- DATABASE MAPPING : region ( VARCHAR ) 
    public void setRegion( String region ) {
        this.region = region;
    }
    public String getRegion() {
        return this.region;
    }

    //--- DATABASE MAPPING : ip ( VARCHAR ) 
    public void setIp( String ip ) {
        this.ip = ip;
    }
    public String getIp() {
        return this.ip;
    }

    //--- DATABASE MAPPING : port ( VARCHAR ) 
    public void setPort( String port ) {
        this.port = port;
    }
    public String getPort() {
        return this.port;
    }

    //--- DATABASE MAPPING : user ( VARCHAR ) 
    public void setUser( String user ) {
        this.user = user;
    }
    public String getUser() {
        return this.user;
    }

    //--- DATABASE MAPPING : user_pwd ( VARCHAR ) 
    public void setUserPwd( String userPwd ) {
        this.userPwd = userPwd;
    }
    public String getUserPwd() {
        return this.userPwd;
    }

    //--- DATABASE MAPPING : traffic ( BIGINT ) 
    public void setTraffic( Long traffic ) {
        this.traffic = traffic;
    }
    public Long getTraffic() {
        return this.traffic;
    }

    //--- DATABASE MAPPING : traffic_name ( VARCHAR ) 
    public void setTrafficName( String trafficName ) {
        this.trafficName = trafficName;
    }
    public String getTrafficName() {
        return this.trafficName;
    }

    //--- DATABASE MAPPING : createdate ( DATETIME ) 
    public void setCreatedate( Date createdate ) {
        this.createdate = createdate;
    }
    public Date getCreatedate() {
        return this.createdate;
    }

    //--- DATABASE MAPPING : createby ( VARCHAR ) 
    public void setCreateby( String createby ) {
        this.createby = createby;
    }
    public String getCreateby() {
        return this.createby;
    }

    //--- DATABASE MAPPING : modifydate ( DATETIME ) 
    public void setModifydate( Date modifydate ) {
        this.modifydate = modifydate;
    }
    public Date getModifydate() {
        return this.modifydate;
    }

    //--- DATABASE MAPPING : modifyby ( VARCHAR ) 
    public void setModifyby( String modifyby ) {
        this.modifyby = modifyby;
    }
    public String getModifyby() {
        return this.modifyby;
    }

    //--- DATABASE MAPPING : status ( INT ) 
    public void setStatus( Integer status ) {
        this.status = status;
    }
    public Integer getStatus() {
        return this.status;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(name);
        sb.append("|");
        sb.append(region);
        sb.append("|");
        sb.append(ip);
        sb.append("|");
        sb.append(port);
        sb.append("|");
        sb.append(user);
        sb.append("|");
        sb.append(userPwd);
        sb.append("|");
        sb.append(traffic);
        sb.append("|");
        sb.append(trafficName);
        sb.append("|");
        sb.append(createdate);
        sb.append("|");
        sb.append(createby);
        sb.append("|");
        sb.append(modifydate);
        sb.append("|");
        sb.append(modifyby);
        sb.append("|");
        sb.append(status);
        return sb.toString(); 
    } 

}
