/*
 * Created on 18 十月 2017 ( Time 09:23:54 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package cn.mxlog.sscloud.model;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "user_traffic"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="user_traffic", catalog="ss_cloud" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="UserTraffic.countAll", query="SELECT COUNT(X) FROM UserTraffic x" )
} )
public class UserTraffic implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="start_date")
    private Date       startDate    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="end_date")
    private Date       endDate      ;

    @Column(name="userId")
    private Integer userId;

    @Column(name="traffic")
    private Long       traffic      ;

    @Column(name="traffic_used")
    private Long       trafficUsed  ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdate")
    private Date       createdate   ;

    @Column(name="createby", length=255)
    private String     createby     ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modifydate")
    private Date       modifydate   ;

    @Column(name="modifyby", length=255)
    private String     modifyby     ;

    @Column(name="status")
    private Integer    status       ;

	// "userId" (column "user_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
//    @OneToOne(cascade = {CascadeType.ALL})
//    @JoinColumn(name="user_id", referencedColumnName="id")
//    private User user        ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public UserTraffic() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : start_date ( DATETIME ) 
    public void setStartDate( Date startDate ) {
        this.startDate = startDate;
    }
    public Date getStartDate() {
        return this.startDate;
    }

    //--- DATABASE MAPPING : end_date ( DATETIME ) 
    public void setEndDate( Date endDate ) {
        this.endDate = endDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }

    //--- DATABASE MAPPING : traffic ( BIGINT ) 
    public void setTraffic( Long traffic ) {
        this.traffic = traffic;
    }
    public Long getTraffic() {
        if(this.traffic == null){
            return 0l;
        }
        return this.traffic;
    }

    //--- DATABASE MAPPING : traffic_used ( BIGINT ) 
    public void setTrafficUsed( Long trafficUsed ) {
        this.trafficUsed = trafficUsed;
    }
    public Long getTrafficUsed() {
        if(this.trafficUsed == null){
            return 0l;
        }
        return this.trafficUsed;
    }

    //--- DATABASE MAPPING : createdate ( DATETIME ) 
    public void setCreatedate( Date createdate ) {
        this.createdate = createdate;
    }
    public Date getCreatedate() {
        return this.createdate;
    }

    //--- DATABASE MAPPING : createby ( VARCHAR ) 
    public void setCreateby( String createby ) {
        this.createby = createby;
    }
    public String getCreateby() {
        return this.createby;
    }

    //--- DATABASE MAPPING : modifydate ( DATETIME ) 
    public void setModifydate( Date modifydate ) {
        this.modifydate = modifydate;
    }
    public Date getModifydate() {
        return this.modifydate;
    }

    //--- DATABASE MAPPING : modifyby ( VARCHAR ) 
    public void setModifyby( String modifyby ) {
        this.modifyby = modifyby;
    }
    public String getModifyby() {
        return this.modifyby;
    }

    //--- DATABASE MAPPING : status ( INT ) 
    public void setStatus( Integer status ) {
        this.status = status;
    }
    public Integer getStatus() {
        return this.status;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------


    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(startDate);
        sb.append("|");
        sb.append(endDate);
        sb.append("|");
        sb.append(traffic);
        sb.append("|");
        sb.append(trafficUsed);
        sb.append("|");
        sb.append(createdate);
        sb.append("|");
        sb.append(createby);
        sb.append("|");
        sb.append(modifydate);
        sb.append("|");
        sb.append(modifyby);
        sb.append("|");
        sb.append(status);
        return sb.toString(); 
    } 

}
