/*
 * Created on 18 十月 2017 ( Time 09:23:54 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package cn.mxlog.sscloud.model;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "user_order"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="user_order", catalog="ss_cloud" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="UserOrder.countAll", query="SELECT COUNT(X) FROM UserOrder x" )
} )
public class UserOrder implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="order_no", length=255)
    private String     orderNo      ;

    @Column(name="traffic")
    private Long       traffic      ;

    @Column(name="quantity")
    private Integer    quantity     ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="order_date")
    private Date       orderDate    ;

    @Column(name="price")
    private BigDecimal price        ;

    @Column(name="paymethod")
    private Integer    paymethod    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="pay_date")
    private Date       payDate      ;

    @Column(name="description", length=500)
    private String     description  ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdate")
    private Date       createdate   ;

    @Column(name="createby", length=255)
    private String     createby     ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modifydate")
    private Date       modifydate   ;

    @Column(name="modifyby", length=255)
    private String     modifyby     ;

    @Column(name="status")
    private Integer    status       ;

	// "userId" (column "user_id") is not defined by itself because used as FK in a link 
	// "comboId" (column "combo_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToOne
    @JoinColumn(name="combo_id", referencedColumnName="id")
    private Combo combo       ;

    @OneToOne
    @JoinColumn(name="user_id", referencedColumnName="id")
    private User user        ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public UserOrder() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : order_no ( VARCHAR ) 
    public void setOrderNo( String orderNo ) {
        this.orderNo = orderNo;
    }
    public String getOrderNo() {
        return this.orderNo;
    }

    //--- DATABASE MAPPING : traffic ( BIGINT ) 
    public void setTraffic( Long traffic ) {
        this.traffic = traffic;
    }
    public Long getTraffic() {
        return this.traffic;
    }

    //--- DATABASE MAPPING : quantity ( INT ) 
    public void setQuantity( Integer quantity ) {
        this.quantity = quantity;
    }
    public Integer getQuantity() {
        if(this.quantity == null){
            return 1;
        }
        return this.quantity;
    }

    //--- DATABASE MAPPING : order_date ( DATETIME ) 
    public void setOrderDate( Date orderDate ) {
        this.orderDate = orderDate;
    }
    public Date getOrderDate() {
        return this.orderDate;
    }

    //--- DATABASE MAPPING : price ( DECIMAL ) 
    public void setPrice( BigDecimal price ) {
        this.price = price;
    }
    public BigDecimal getPrice() {
        return this.price;
    }

    //--- DATABASE MAPPING : paymethod ( INT ) 
    public void setPaymethod( Integer paymethod ) {
        this.paymethod = paymethod;
    }
    public Integer getPaymethod() {
        return this.paymethod;
    }

    //--- DATABASE MAPPING : pay_date ( DATETIME ) 
    public void setPayDate( Date payDate ) {
        this.payDate = payDate;
    }
    public Date getPayDate() {
        return this.payDate;
    }

    //--- DATABASE MAPPING : description ( VARCHAR ) 
    public void setDescription( String description ) {
        this.description = description;
    }
    public String getDescription() {
        return this.description;
    }

    //--- DATABASE MAPPING : createdate ( DATETIME ) 
    public void setCreatedate( Date createdate ) {
        this.createdate = createdate;
    }
    public Date getCreatedate() {
        return this.createdate;
    }

    //--- DATABASE MAPPING : createby ( VARCHAR ) 
    public void setCreateby( String createby ) {
        this.createby = createby;
    }
    public String getCreateby() {
        return this.createby;
    }

    //--- DATABASE MAPPING : modifydate ( DATETIME ) 
    public void setModifydate( Date modifydate ) {
        this.modifydate = modifydate;
    }
    public Date getModifydate() {
        return this.modifydate;
    }

    //--- DATABASE MAPPING : modifyby ( VARCHAR ) 
    public void setModifyby( String modifyby ) {
        this.modifyby = modifyby;
    }
    public String getModifyby() {
        return this.modifyby;
    }

    //--- DATABASE MAPPING : status ( INT ) 
    public void setStatus( Integer status ) {
        this.status = status;
    }
    public Integer getStatus() {
        return this.status;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setCombo( Combo combo ) {
        this.combo = combo;
    }
    public Combo getCombo() {
        return this.combo;
    }

    public void setUser( User user ) {
        this.user = user;
    }
    public User getUser() {
        return this.user;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(orderNo);
        sb.append("|");
        sb.append(traffic);
        sb.append("|");
        sb.append(quantity);
        sb.append("|");
        sb.append(orderDate);
        sb.append("|");
        sb.append(price);
        sb.append("|");
        sb.append(paymethod);
        sb.append("|");
        sb.append(payDate);
        sb.append("|");
        sb.append(description);
        sb.append("|");
        sb.append(createdate);
        sb.append("|");
        sb.append(createby);
        sb.append("|");
        sb.append(modifydate);
        sb.append("|");
        sb.append(modifyby);
        sb.append("|");
        sb.append(status);
        return sb.toString(); 
    } 

}
