server:
  port: 8083
  session:
    timeout: 1800000

spring:
  session:
     store-type: none

  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/ss_cloud?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: mp%root
    max-wait: 10000
    maximum-pool-size: 50
    max-idle: 10
    min-idle: 5
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  redis:
    host: 192.168.0.124
    port: 6379

logging:
  level: debug


