debug: false

server:
  port: 8083
spring:
  session:
    store-type: redis
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ss_cloud?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: mp%root
    max-wait: 10000
    maximum-pool-size: 50
    max-idle: 10
    min-idle: 5
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  redis:
      host: localhost
      port: 6379
logging:
  level: error